#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_BICICLETAS 15
#define MAX_UTENTES 50
#define MAX_STRING 100
#define MAX_CODUTENTE 9999
#define MIN_CODUTENTE 1

#endif // CONSTANTES_H_INCLUDED
